// =============================================
// src/utils/roundupSchema.js
// News Roundup Database Schema & Utilities
// =============================================

/**
 * Database Structure:
 * /news-roundups/{roundupId}
 *   - id: string (YYYY-MM-DD format)
 *   - title: string
 *   - date: string (ISO format)
 *   - createdAt: timestamp
 *   - updatedAt: timestamp
 *   - createdBy: string (admin uid)
 *   - status: 'draft' | 'published'
 *   - posts: array of post IDs in order
 *   - postDetails: { [postId]: { title, imageUrl, category, publishedAt } }
 *   - analytics: { views, clicks, shares }
 *   - isAutoGenerated: boolean
 */

export const ROUNDUP_STATUS = {
  DRAFT: 'draft',
  PUBLISHED: 'published'
};

export const createRoundupId = (date = new Date()) => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const createRoundupTemplate = (adminUid, isAutoGenerated = false) => {
  const now = new Date();
  const roundupId = createRoundupId(now);
  
  return {
    id: roundupId,
    title: `Today's News Roundup - ${formatDateForTitle(now)}`,
    date: now.toISOString(),
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    createdBy: adminUid,
    status: ROUNDUP_STATUS.DRAFT,
    posts: [],
    postDetails: {},
    analytics: {
      views: 0,
      clicks: 0,
      shares: 0
    },
    isAutoGenerated
  };
};

export const formatDateForTitle = (date) => {
  const options = { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  };
  return new Date(date).toLocaleDateString('en-IN', options);
};

export const isSameDay = (date1, date2) => {
  const d1 = new Date(date1);
  const d2 = new Date(date2);
  return (
    d1.getFullYear() === d2.getFullYear() &&
    d1.getMonth() === d2.getMonth() &&
    d1.getDate() === d2.getDate()
  );
};

export const getTodayRoundupId = () => {
  return createRoundupId(new Date());
};

export const scorePost = (post) => {
  // Scoring algorithm for auto-generation
  const views = post.analytics?.views || 0;
  const likes = post.analytics?.likes || 0;
  const comments = post.analytics?.comments || 0;
  const shares = post.analytics?.shares || 0;
  
  // Weighted scoring
  const engagementScore = (likes * 2) + (comments * 3) + (shares * 5);
  const viewScore = Math.log10(views + 1) * 10;
  const recencyBonus = isRecent(post.publishedAt) ? 20 : 0;
  
  return engagementScore + viewScore + recencyBonus;
};

const isRecent = (publishedAt) => {
  const postDate = new Date(publishedAt);
  const now = new Date();
  const hoursDiff = (now - postDate) / (1000 * 60 * 60);
  return hoursDiff <= 6; // Posts from last 6 hours get bonus
};

export const autoSelectPosts = (allPosts, maxPosts = 10) => {
  const today = new Date();
  
  // Filter posts from today only
  const todayPosts = allPosts.filter(post => {
    if (!post.publishedAt) return false;
    return isSameDay(post.publishedAt, today);
  });
  
  // Score and sort posts
  const scoredPosts = todayPosts.map(post => ({
    ...post,
    score: scorePost(post)
  }));
  
  scoredPosts.sort((a, b) => b.score - a.score);
  
  // Return top posts
  return scoredPosts.slice(0, maxPosts);
};

export const extractPostDetails = (post) => {
  return {
    id: post.id,
    title: post.title || post.content?.substring(0, 100) || 'Untitled',
    imageUrl: post.imageUrl || post.mediaContent?.items?.[0]?.url || '',
    thumbnailUrl: post.thumbnailUrl || post.mediaContent?.items?.[0]?.thumbnailUrl || '',
    category: post.category || 'General',
    publishedAt: post.publishedAt || post.createdAt,
    type: post.type || 'article',
    author: post.author || {},
    excerpt: post.excerpt || post.content?.substring(0, 150) || ''
  };
};

export const validateRoundup = (roundup) => {
  const errors = [];
  
  if (!roundup.title || roundup.title.trim() === '') {
    errors.push('Title is required');
  }
  
  if (!roundup.posts || roundup.posts.length === 0) {
    errors.push('At least one post is required');
  }
  
  if (roundup.posts && roundup.posts.length > 20) {
    errors.push('Maximum 20 posts allowed');
  }
  
  return {
    isValid: errors.length === 0,
    errors
  };
};
